name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to deploy'
        required: true
        type: string

jobs:
  deploy-to-production:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}

      - name: Deploy to Production
        run: |
          echo "Copying files to production server..."
          # Create a temporary script to handle the deployment
          cat > deploy.sh << 'EOF'
          #!/bin/bash
          set -e
          
          # Clean and create directory
          rm -rf /home/beny/gtask/*
          mkdir -p /home/beny/gtask
          
          # Copy files
          cp package.json /home/beny/gtask/
          cp package-lock.json /home/beny/gtask/
          cp -r dist /home/beny/gtask/
          
          # Install dependencies
          cd /home/beny/gtask
          npm ci
          
          # Kill any existing process
          lsof -ti:3000 | xargs kill -9 2>/dev/null || true
          
          # Start server
          nohup npm run preview -- --host 0.0.0.0 --port 3000 > /dev/null 2>&1 &
          
          # Wait for server to start
          sleep 5
          
          # Check if server is running
          if curl -s http://localhost:3000 > /dev/null; then
            echo "Production server is running successfully!"
          else
            echo "Production server failed to start!"
            exit 1
          fi
          EOF
          
          # Make script executable and run it
          chmod +x deploy.sh
          ./deploy.sh
          
          echo "Production deployment complete!" 